# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# test circleci
version: 2
jobs:
  backend-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/backend-opal

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - backend-dependencies-{{ checksum "./backend-opal/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - backend-dependencies-

      - run: 
          name: install packages in backend
          command: 'cd backend-opal && npm install'

      - save_cache:
          paths:
            - ./backend-opal/node_modules
          key: backend-dependencies-{{ checksum "./backend-opal/package-lock.json" }}

      # run tests!
      - run: 
          name: backend test
          command: 'cd backend-opal && npm test'

  frontend-test:
    docker: 
      - image: circleci/node:10.16.3

    working_directory: ~/frontend-opal

    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-dependencies-{{ checksum "./frontend-opal/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - frontend-dependencies-

      - run:
          name: install packages in frontend
          command: 'cd frontend-opal && npm install'

      - save_cache:
          paths:
            - ./frontend-opal/node_modules
          key: frontend-dependencies-{{ checksum "./frontend-opal/package-lock.json" }}

      - run:
          name: frontend test
          command: 'cd frontend-opal && npm test'

workflows:
  version: 2
  test-backend-frontend:
    jobs:
      - backend-test:
          filters:
            branches:
              only: 
                - master
                - honda-issue70-ci
      - frontend-test:
          filters:
            branches:
              only: 
                - master
                - honda-issue70-ci
